config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#top'
  get 'static_pages/home'=>'static_pages#home',as:'home'
  get 'static_pages/help'=>'static_pages#help',as:'help'
  get 'static_pages/about'=>'static_pages/about',as:'about'
  get  '/signup'=> 'users#new',as:'new'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :first_name, :last_name, :email

  def initialize(attributes = {})
    @first_name = attributes[:first_name]
    @last_name = attributes[:last_name]
    @email = attributes[:email]
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def formatted_email
    "#{self.full_name} <#{@email}>"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  def top
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
 <div class="footer">
     <%=link_to "Ruby on Rails Tutorial","#",class:"footer_text"%>
     <%=link_to "About","#",class:"footer_text2"%>
     <%=link_to "Contact","#",class:"footer_text2"%>
     <%=link_to "News","#",class:"footer_text2"%>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <div class="top">
    <div class="title"><h1><%= link_to "sample app", '/' ,class:"text"%></h1></div>
    <div class="title_right">
      <%=link_to "Home",home_path, class:"title_right_text"%> 
      <%=link_to "help",help_path, class:"title_right_text"%>  
      <%=link_to "Log in","#", class:"title_right_text"%>  
    </div>
  </div>  
    <title><%= full_title(yield(:title)) %></title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
<%= link_to image_tag("kitten.jpg"),"#"%>

app/views/static_pages/top.html.erb
<div class="body">
   <div class="top_text">
   <h1>Welcome to the Sample App</h1>
   <p>This is the home page for the Ruby on Rails Tutorial sample application.</p>
   </div>
    <div class="button">
      <p><%= link_to "sign up now!",new_path,class:"butten_text"%></p>
    </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>